### PR TITLE
remove html decode of names

### PR DESCRIPTION
**Pull request by timothydm42**
regarding: https://almtools.ldschurch.org/fhjira/browse/SITE-2062

### CODE REVIEW

**Comment by rosemariesadler** [comment]
Something we've found is that the version of safari needs to be updated for tests. In the wct.conf file, if you change all the versions of mac to 13 instead of 12 and change safari to 11.1 instead of 11, the tests should pass.

**Comment by rosemariesadler** [comment]
What version is this going to be released as?

**Comment by timothydm42** [comment]
I suppose this is a major change, since it could break whomever may be relying on the decode

**Comment by rosemariesadler** [comment]
If it were me, I'd release it as a patch because it really is broken and you would have to be doing a weird workaround to rely on the behavior where you encode the data before you pass it in. Based on the component catalog, home and tree are the only things that rely on it, so if you aren't depending on the broken functionality, I'd say it's fine to release as a patch.

**Comment by timothydm42** [comment]
Ok i'm persuaded :)

**Comment by timothydm42** [comment]
Thanks for all your help @rosemariesadler

**Pull request merged**
